# Generated by Django 5.0.2 on 2024-02-13 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_profile_scapes_followed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(max_length=2000)),
                ('scape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.scape')),
            ],
        ),
    ]
