# Generated by Django 4.2.10 on 2024-02-15 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='tags',
            new_name='plant_tags',
        ),
    ]
