# Generated by Django 4.2.10 on 2024-03-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scape',
            name='plants',
            field=models.ManyToManyField(blank=True, to='catalog.plant'),
        ),
    ]
